print('what is your name?')
myName = input()
print('It is good to meet you, ' + myName)
print('the length of your name is: ')
print(len(myName))
print('what is your age?')
myAge = input()
print("you'll be " + str(int(myAge)+1)+ "years old in a year")
